### PR TITLE
Implements a separate adjustment set for the propensity score, and corrects variance estimation if `id` is provided

### PR DESCRIPTION
**Pull request by nt-williams**

### CODE REVIEW

**Review by nhejazi — COMMENTED** [review]
this looks great! thanks for the quick work on this @nt-williams. as a final check, would you mind adding a short unit test for the repeated measures `ids`? (i don't think is necessary for `g_adjust` since it's already checked with an `assertthat`.) for this kind of test, one would, e.g., run the same NDE/NIE code on a dataset with repeated measures, once ignoring the IDs and another time using them. it should be the case that the point estimates match closely (up to issues with cross-validation) while the standard error estimate for the case where the repeated measures are ignored will be much bigger than when using them (since dividing by different numbers of units).

**Comment by nhejazi** [comment]
hi @nt-williams, will you be able to make the edits noted above? there's not a particular rush but it'll be important to test/check the changes prior to their use in an analysis

**Comment by nt-williams** [comment]
Hey! @nhejazi , I removed the changes I had made to `b_score` and `q_score`. I'll work on implementing a test in the coming days.

**Comment by nt-williams** [comment]
@nhejazi Added a test for larger variance. Let me know if there's anything else!

**Comment by nhejazi** [comment]
lgtm, thanks @nt-williams!

**Pull request merged**
