### PR TITLE
Support Two-Phase Sampling Design

### PR DESCRIPTION
**Pull request by PhilBoileau**
This PR partially addresses issue #36. `medoutcon()` now supports two-phase sampling designs with known sampling weights.

### CODE REVIEW

**Comment by PhilBoileau** [comment]
I think these test failures point towards an issue with `expect_equal()`'s behaviour when the `tol` argument is specified.
```
expect_equal(c(0, 0, 0, 1, 1, 1), rep(0, 6), tol = 0.5)
Error: c(0, 0, 0, 1, 1, 1) not equal to rep(0, 6).
3/6 mismatches (average diff: 1)
[4] 1 - 0 == 1
[5] 1 - 0 == 1
[6] 1 - 0 == 1
```
The error messages can make failures look worse than they really are, especially when we're attempting to assess estimator bias. The randomness of the tests complicates reproducibility, too. These tests effectively assess convergence in probability. All tests pass locally (macOS), but I suspect that larger sample sizes are needed to consistently pass all tests in all environments and with any random seed. 

I suggest we remove most tests assessing the closeness of (nuisance) estimator outputs to ground truth. Testing for MSEs near zero, which is already done for all estimators, will identify biased estimators. Convergence in expectation should also be achieved in smaller sample sizes, and so test results will be more easily reproduced.

**Comment by nhejazi** [comment]
Thanks for these changes. As of [17fb00a](https://github.com/nhejazi/medoutcon/pull/38/commits/17fb00a2910595e31d006544bdec85bb97b89011) I'm still working through a few lingering details of the implementation but will complete this review very soon; details to come then.

Regarding testing, I agree and think we should move towards better-designed testing strategies. I recall the implementation of these estimators being very hard to debug and the strictness of the unit tests is, in part, a function of that, though they were not "well-designed" regardless. Any changes welcome.

**Comment by PhilBoileau** [comment]
Thanks for the thorough review! Looking forward to going through your comments.

Test driven design strategies for estimators/stochastic functions is really difficult. I've been struggling for a while to find the correct tradeoff between accuracy and computation time. I'd be happy to discuss more during our next meeting.

**Review by nhejazi — CHANGES_REQUESTED** [review]
finished working through this and making minor edits throughout; I had to convince myself that the intermediate confounder (`Z`) could be used in the two-phase sampling procedure (I think it can). I'm now seeing all tests pass locally except for the comparison of estimated V nuisance parameter to the two-phase sampling-corrected EIF -- any sense why these are so different?

also, from what I can tell, the updates you've made support two-phase sampling corrections, including for aggressively estimated weights, as long as the weights are computed externally and use the full set of pre-mediator variables and outcome, (W, A, Z, Y); so, even though untested at the moment, this should work for settings beyond known weights.

**Comment by PhilBoileau** [comment]
Thanks for going through the PR! Glad that you’re on board with the application of these sampling weights to the mediator-outcome confounder setting.

I’m not sure why that test is failing now… it shouldn’t have been affected by any of the recent changes. I was observing similarly odd behaviour when testing the fitting mechanism for the EIF. Using a Random Forest instead of HAL fixed the problem. I’ll investigate early next week.

I made these modifications so that more general sampling weight estimation procedures could implemented in the future with (hopefully) little effort. I can work on this while we wrap up the NDECONF project.

**Pull request merged**
